// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4ITsFqsfqUv6qi5ELBDQ1ZaJgqNHHjRY',
    appId: '1:408497469187:web:c2064d1c1ce07c7e759b36',
    messagingSenderId: '408497469187',
    projectId: 'mapapp-b2513',
    authDomain: 'mapapp-b2513.firebaseapp.com',
    storageBucket: 'mapapp-b2513.firebasestorage.app',
    measurementId: 'G-K3YCBLNKQE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBB8wqaH_4Usoqr9hGr6yOLZKi00WEVnQo',
    appId: '1:408497469187:android:fbe152c873500afb759b36',
    messagingSenderId: '408497469187',
    projectId: 'mapapp-b2513',
    storageBucket: 'mapapp-b2513.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-jh4PeiQW3rOX_PJ7BDrFo6euw7O4CQs',
    appId: '1:408497469187:ios:b47b08f8082677c8759b36',
    messagingSenderId: '408497469187',
    projectId: 'mapapp-b2513',
    storageBucket: 'mapapp-b2513.firebasestorage.app',
    iosBundleId: 'com.example.mappapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-jh4PeiQW3rOX_PJ7BDrFo6euw7O4CQs',
    appId: '1:408497469187:ios:a27de861f39f5f5a759b36',
    messagingSenderId: '408497469187',
    projectId: 'mapapp-b2513',
    storageBucket: 'mapapp-b2513.firebasestorage.app',
    iosBundleId: 'com.example.mapapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4ITsFqsfqUv6qi5ELBDQ1ZaJgqNHHjRY',
    appId: '1:408497469187:web:c80af1a7af04f771759b36',
    messagingSenderId: '408497469187',
    projectId: 'mapapp-b2513',
    authDomain: 'mapapp-b2513.firebaseapp.com',
    storageBucket: 'mapapp-b2513.firebasestorage.app',
    measurementId: 'G-YFP2YR7D0H',
  );
}
